server:
  port: 8080
  servlet:
    context-path: /customer-services/api
spring:
  application:
    name: customer-services
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    com.pichincha.customer: DEBUG
    org.springframework.security: DEBUG